### ISSUE TITLE
A question about pose track

### ISSUE THREAD

**Issue by lc4321** [YuliangXiu/PoseFlow#4]
About PoseTrack ECCV 2018 Challenge, how to generate the pose data just for testing Multi-Person Pose Tracking? Is it generated by Multi-Person Pose Estimation or just extracted pose_coordinate from /posetrack2018/posetrack_data/annotations/jsons? If only for evaluating Multi-Person Pose Tracking, should the original pose data be labeled?

**Comment by YuliangXiu** [comment]
If the only thing you want to do is testing the tracking performance, you can obtain the pose_coordinates from trainset and validset of PoseTrack dataset(json or mat files in posetrack_data/annotations). Otherwise, you need to generate pose_coordinates via Multi-Person Pose Estimation Framework, such as [AlphaPose](https://github.com/MVIG-SJTU/AlphaPose).

**Comment by YuliangXiu** [comment]
[PoseFlow(General Version)](https://github.com/YuliangXiu/PoseFlow#for-any-datasets-general-version) has already been released, now you can do pose tracking on any private dataset, the new version also supports pose tracking results visualization.
